### ISSUE TITLE
2017-pw-01 and 2011-01 are implausibly close together

### ISSUE THREAD

**Issue by goatchurchprime** [CaveSurveying/CUCCexposurveyissues#39]
Very overlapping cave passages which do not connect.

On the survex data they are 23m apart, and vertically 63m apart.  

Need to check the records about their locations, which are possibly wrong.

**Comment by pwithnall** [comment]
They are definitely separate entrances on the surface, and are both physically tagged (although `2017-pw-01` now has a kataster number of 1623/277 as per https://github.com/CaveSurveyGIS/CUCCexposurveyissues/issues/8).

They likely both end up in the same large breakdown chamber (the legs at the bottom of `1623/2017-pw-01/gardeningshoots`), with `2011-01` entering via a different aven. However, to the best of my knowledge, `2011-01` wasn’t reexplored in 2017 or since.

I guess the fix here is to do a surface survey from one to the other, or get a more accurate GPS location for the two entrances.

**Comment by BeckaLawson** [comment]
It would be good to check this in the field but for now I've added in 2011-01 as a separate cave in the Austrian kataster so it can be assigned its own number. If the two caves are connected in the future that's fine.
